"use strict";
var valor;
valor = true;
valor = 1000;
valor = "Hcode";
console.log(typeof valor);
var despesaFixa;
var despesaVariavel;
despesaFixa = "150";
despesaVariavel = 320;
console.log(despesaFixa + despesaVariavel);
var itens = [];
